"""add idempotency uniqueness

Revision ID: 0b06c0d2012d
Revises: 03f59246d7d8
Create Date: 2026-10-04 20:31:26.082922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b06c0d2012d'
down_revision: Union[str, Sequence[str], None] = '03f59246d7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_jobs_idempotency_key', 'jobs', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_jobs_idempotency_key', 'jobs', type_='unique')
    # ### end Alembic commands ###
